# Generated by Django 2.1.3 on 2018-11-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0002_auto_20181113_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='stopped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
