# Generated by Django 2.1.3 on 2018-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0005_auto_20181113_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sessionType',
            new_name='session_type',
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('1', 'starting'), ('2', 'running'), ('3', 'stopped')], default='1', max_length=10),
        ),
    ]
