# Generated by Django 2.1.3 on 2018-11-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0006_auto_20181113_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('starting', 'starting'), ('running', 'running'), ('stopped', 'stopped')], default='starting', max_length=10),
        ),
    ]
