# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('testsession', '0007_auto_20181114_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='testsession_textpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=20000, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
