# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-21 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0010_auto_20181121_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 21, 16, 13, 31, 975546, tzinfo=utc)),
        ),
    ]
