# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0011_auto_20181121_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
