# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0012_auto_20181122_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='api_endpoint',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
