# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0013_auto_20181122_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='exposed_api',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='session',
            name='log',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='/files/log'),
        ),
    ]
