# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0014_auto_20181204_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.CharField(max_length=20000, null=True)),
                ('response', models.CharField(max_length=20000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='log',
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testsession.Session'),
        ),
    ]
