# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0016_scenario_scenariocase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsession.Scenario'),
            preserve_default=False,
        ),
    ]
