# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    Scenario = apps.get_model('testsession', 'Scenario')
    try:
        Scenario.objects.get(pk=1)
    except Scenario.DoesNotExist:
        Scenario.objects.create(pk=1, standard='Example scenario')

def reverse_func(apps, schema_editor):
    pass
        
class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0016_scenario_scenariocase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='session',
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AddField(
            model_name='session',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsession.Scenario'),
            preserve_default=False,
        ),
    ]
