# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-10 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0020_auto_20181210_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocase',
            name='HTTP_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=20),
        ),
    ]
