# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0021_scenariocase_http_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='scenario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsession.Scenario'),
        ),
    ]
