# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0026_session_json_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocase',
            name='url',
            field=models.CharField(default='/zrc/api/v1/zaken', max_length=200),
            preserve_default=False,
        ),
    ]
