# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0027_auto_20181212_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='port',
            field=models.PositiveIntegerField(default=8080),
        ),
    ]
