# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0029_auto_20181217_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='VNGEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='api_endpoint',
            field=models.ManyToManyField(to='testsession.VNGEndpoint'),
        ),
    ]
