# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0032_auto_20181217_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenariocase',
            old_name='HTTP_method',
            new_name='http_method',
        ),
        migrations.RemoveField(
            model_name='scenariocase',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='sessiontype',
            name='docker_image',
        ),
        migrations.AddField(
            model_name='scenariocase',
            name='vng_endpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsession.SessionType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vngendpoint',
            name='docker_image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vngendpoint',
            name='session_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsession.SessionType'),
            preserve_default=False,
        ),
    ]
