# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0033_auto_20181217_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocase',
            name='vng_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsession.VNGEndpoint'),
        ),
    ]
