# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0036_auto_20181217_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='exposed_api',
        ),
        migrations.AddField(
            model_name='vngendpoint',
            name='exposed_api',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
