# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0038_auto_20181218_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposedurl',
            name='exposed_url',
            field=models.CharField(default='tst', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
