# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0039_auto_20181218_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='session',
            name='port',
        ),
        migrations.AddField(
            model_name='vngendpoint',
            name='port',
            field=models.PositiveIntegerField(default=8080),
        ),
    ]
