# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0040_auto_20181218_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='json_result',
        ),
        migrations.RemoveField(
            model_name='session',
            name='test_result',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='name',
        ),
        migrations.AddField(
            model_name='testsession',
            name='json_result',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='test_result',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='/files/log'),
        ),
    ]
