# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0041_auto_20181218_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='test',
        ),
        migrations.AddField(
            model_name='testsession',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsession.Session'),
            preserve_default=False,
        ),
    ]
