# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0043_auto_20181218_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='vng_endpoint',
        ),
        migrations.AddField(
            model_name='exposedurl',
            name='test_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsession.TestSession'),
            preserve_default=False,
        ),
    ]
