# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    VNGEndpoint = apps.get_model("testsession", "VNGEndpoint")
    SessionType = apps.get_model("testsession", "TestSession")
    if not VNGEndpoint.objects.filter(id=1):
        VNGEndpoint.objects.create(name='Example', url='https://vng.nl', session_type=SessionType.objects.first())


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0044_auto_20181218_1715'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='exposedurl',
            name='test_session',
        ),
        migrations.AddField(
            model_name='vngendpoint',
            name='test_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsession.TestSession'),
            preserve_default=False,
        ),
    ]
