# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0047_auto_20181220_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vngendpoint',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
