# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0048_auto_20181220_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='scenariocase',
            name='result',
        ),
        migrations.AddField(
            model_name='report',
            name='scenario_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsession.ScenarioCase'),
        ),
        migrations.AddField(
            model_name='report',
            name='session_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsession.SessionLog'),
        ),
    ]
