# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0050_report_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsession',
            name='test_file',
        ),
        migrations.RemoveField(
            model_name='vngendpoint',
            name='test_session',
        ),
        migrations.AddField(
            model_name='exposedurl',
            name='test_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsession.TestSession'),
        ),
        migrations.AddField(
            model_name='vngendpoint',
            name='test_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='/files/uploaded_files'),
        ),
    ]
