# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0051_auto_20190108_1151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('scenario_case', 'session_log')]),
        ),
    ]
