# Generated by Django 2.2a1 on 2019-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0054_session_build_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
