# Generated by Django 2.2a1 on 2019-02-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0056_auto_20190206_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposedurl',
            name='docker_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
