# Generated by Django 2.2a1 on 2019-03-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0059_auto_20190225_1001'),
        ('testsession', '0059_auto_20190305_1542'),
    ]

    operations = [
    ]
