# Generated by Django 2.2a1 on 2019-03-05 09:32

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0010_auto_20180414_2058'),
        ('testsession', '0060_auto_20190305_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='vngendpoint',
            name='test_file',
            field=filer.fields.file.FilerFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File'),
        ),
    ]
