# Generated by Django 2.2a1 on 2019-03-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0061_auto_20190304_0942'),
        ('testsession', '0060_merge_20190306_1008'),
    ]

    operations = [
    ]
