# Generated by Django 2.2a1 on 2019-03-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0061_vngendpoint_test_file'),
        ('testsession', '0060_auto_20190305_1516'),
    ]

    operations = [
    ]
