# Generated by Django 2.2a1 on 2019-03-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0063_auto_20190311_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposedurl',
            old_name='exposed_url',
            new_name='subdomain',
        ),
    ]
