# Generated by Django 2.2a1 on 2019-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0063_auto_20190311_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='authentication',
            field=models.CharField(choices=[('JWT', 'jwt'), ('Authorization header', 'header'), ('No Authorization', 'no auth')], default='No Authorization', max_length=20),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='client_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sessiontype',
            name='secret',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
