# Generated by Django 2.2a1 on 2019-03-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0063_auto_20190311_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposedurl',
            name='exposed_url',
            field=models.CharField(max_length=200),
        ),
    ]
