# Generated by Django 2.2a1 on 2019-04-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0065_sessiontype_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Sessie', 'verbose_name_plural': 'Sessie'},
        ),
        migrations.AlterModelOptions(
            name='sessiontype',
            options={'verbose_name': 'Sessie type', 'verbose_name_plural': 'Sessie type'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'verbose_name': 'Test Sessie', 'verbose_name_plural': 'Test Sessie'},
        ),
        migrations.AlterField(
            model_name='exposedurl',
            name='subdomain',
            field=models.CharField(max_length=200, unique=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsession.SessionType', verbose_name='Sessie type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gestart op'),
        ),
        migrations.AlterField(
            model_name='session',
            name='stopped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gestopt op'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='application',
            field=models.CharField(max_length=200, null=True, verbose_name='Applicatie'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='role',
            field=models.CharField(max_length=200, null=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='standard',
            field=models.CharField(max_length=200, null=True, verbose_name='Standaard'),
        ),
        migrations.AlterField(
            model_name='sessiontype',
            name='version',
            field=models.CharField(max_length=200, null=True, verbose_name='Versie'),
        ),
        migrations.CreateModel(
            name='QueryParamsScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expected_value', models.CharField(default='*', max_length=50)),
                ('scenario_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsession.ScenarioCase')),
            ],
        ),
    ]
