# Generated by Django 2.2a1 on 2019-04-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0066_auto_20190404_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocase',
            name='http_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=20),
        ),
    ]
