# Generated by Django 2.2a1 on 2019-04-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0067_auto_20190408_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
