# Generated by Django 2.2a1 on 2019-04-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0068_session_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsession.SessionType')),
            ],
            options={
                'unique_together': {('session_type', 'key')},
            },
        ),
    ]
