# Generated by Django 2.2a1 on 2019-04-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0069_injectheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='vngendpoint',
            name='path',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
