# Generated by Django 2.2a1 on 2019-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0070_vngendpoint_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vngendpoint',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
