# Generated by Django 2.2a1 on 2019-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0070_vngendpoint_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vngendpoint',
            name='path',
            field=models.CharField(default='', help_text='Path url that is appended in the front end page. The path must contain the slash at                             the beginning. E.g. /zrc/api/v1/', max_length=200),
        ),
        migrations.AlterField(
            model_name='vngendpoint',
            name='url',
            field=models.URLField(blank=True, default=None, help_text='Base url (host of the service). E.g. http://ref.tst.vng.cloud, without the ending slash.', null=True),
        ),
    ]
