# Generated by Django 2.2a1 on 2019-05-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0071_auto_20190426_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryparamsscenario',
            name='scenario_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testsession.ScenarioCase'),
        ),
        migrations.AlterField(
            model_name='scenariocase',
            name='vng_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testsession.VNGEndpoint'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testsession.SessionType', verbose_name='Sessie type'),
        ),
        migrations.AlterField(
            model_name='vngendpoint',
            name='session_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testsession.SessionType'),
        ),
    ]
