# Generated by Django 2.2.1 on 2019-05-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0072_auto_20190522_1130'),
        ('testsession', '0072_auto_20190523_1608'),
    ]

    operations = [
    ]
