# Generated by Django 2.2.1 on 2019-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0072_auto_20190522_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
