# Generated by Django 2.2.1 on 2019-05-24 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0073_merge_20190524_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposedurl',
            name='port',
            field=models.PositiveIntegerField(default=8080),
        ),
    ]
