# Generated by Django 2.2.1 on 2019-06-06 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0074_auto_20190524_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontype',
            name='db_data',
            field=models.TextField(blank=True, default=None, null=True),
        )
    ]
