# Generated by Django 2.2.1 on 2019-06-14 10:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0074_auto_20190613_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
