# Generated by Django 2.2.1 on 2019-06-06 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testsession', '0075_auto_20190606_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentBoostrap',
        ),
    ]
