# Generated by Django 2.2a1 on 2019-04-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Verplicht. Maximaal 150 tekens.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
