# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ServerRun',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
