# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-22 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0002_serversun_started'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerSun',
            new_name='ServerRun',
        ),
    ]
