# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0006_auto_20181122_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrun',
            name='log',
            field=models.FileField(blank=True, default=None, upload_to='', verbose_name='/files/log'),
        ),
        migrations.AddField(
            model_name='serverrun',
            name='status',
            field=models.CharField(choices=[('starting', 'starting'), ('running', 'running'), ('stopped', 'stopped')], default='starting', max_length=10),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='validation_file',
            field=models.FileField(upload_to='', verbose_name='/files/uploaded_files'),
        ),
    ]
