# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0007_auto_20181123_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrun',
            name='log',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='/files/log'),
        ),
    ]
