# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0008_auto_20181123_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('client_id', models.TextField()),
                ('secret', models.TextField()),
                ('server_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun')),
            ],
        ),
    ]
