# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0011_auto_20190115_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenarioUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
                ('test_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.TestScenario')),
            ],
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
    ]
