# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0012_auto_20190116_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='client_id',
            new_name='jwt',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='secret',
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterField(
            model_name='testscenariourl',
            name='url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
