# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0016_auto_20190116_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='test_scenario_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servervalidation.TestScenarioUrl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
    ]
