# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0022_auto_20190122_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostmanTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='/files/log')),
            ],
        ),
        migrations.RemoveField(
            model_name='postmantest',
            name='log',
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AddField(
            model_name='postmantestresult',
            name='postman_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.PostmanTest'),
        ),
        migrations.AddField(
            model_name='postmantestresult',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
    ]
