# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0036_auto_20190129_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrun',
            name='percentage_exec',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='serverrun',
            name='status_exec',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterField(
            model_name='postmantestresult',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
    ]
