# Generated by Django 2.2a1 on 2019-02-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0047_auto_20190225_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.RemoveField(
            model_name='postmantest',
            name='validation_file',
        ),
        migrations.AlterField(
            model_name='postmantestresult',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.CreateModel(
            name='ServerHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_key', models.TextField()),
                ('header_value', models.TextField()),
                ('server_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun')),
            ],
        ),
    ]
