# Generated by Django 2.2a1 on 2019-03-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0049_auto_20190305_1542'),
        ('servervalidation', '0050_auto_20190304_0942'),
    ]

    operations = [
    ]
