# Generated by Django 2.2a1 on 2019-03-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0052_auto_20190305_1035'),
        ('servervalidation', '0051_auto_20190305_1516'),
    ]

    operations = [
    ]
