# Generated by Django 2.2a1 on 2019-04-25 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0056_auto_20190411_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrun',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
