# Generated by Django 2.2a1 on 2019-04-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0056_auto_20190411_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpectedPostmanResult',
        ),
    ]
