# Generated by Django 2.2a1 on 2019-04-25 09:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0057_auto_20190425_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpectedPostmanResult',
        ),
        migrations.AddField(
            model_name='serverrun',
            name='last_exec',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Laatste uitvoering'),
        ),
    ]
