# Generated by Django 2.2.1 on 2019-05-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0059_auto_20190510_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenariourl',
            name='url',
            field=models.BooleanField(default=True, help_text='Uncheck it if this variable is not a url but will be still injected in the postman collection.'),
        ),
    ]
