# Generated by Django 2.2a1 on 2019-05-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0060_auto_20190515_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterField(
            model_name='postmantest',
            name='test_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servervalidation.TestScenario'),
        ),
        migrations.AlterField(
            model_name='postmantestresult',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterField(
            model_name='serverheader',
            name='server_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servervalidation.ServerRun'),
        ),
        migrations.AlterField(
            model_name='serverrun',
            name='status',
            field=models.CharField(choices=[('starting', 'starting'), ('running', 'running'), ('shutting down', 'shutting down'), ('stopped', 'stopped'), ('Error deployment', 'error deploy'), ('Scheduled', 'scheduled')], default='starting', max_length=20),
        ),
        migrations.AlterField(
            model_name='serverrun',
            name='test_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servervalidation.TestScenario'),
        ),
        migrations.AlterField(
            model_name='testscenariourl',
            name='test_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servervalidation.TestScenario'),
        ),
        migrations.AlterField(
            model_name='testscenariourl',
            name='url',
            field=models.BooleanField(default=True, help_text='When enabled a single-line field is shown to the user when starting a session. When disabled a multi-line field is shown.'),
        ),
    ]
