# Generated by Django 2.2.1 on 2019-06-14 10:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('servervalidation', '0061_auto_20190522_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenario',
            name='description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
